// Copyright 2022 Pratik R Gupte. See repository licence in LICENSE.md.
// Generated by using Rcpp::compileAttributes() and manually modified

#ifndef pathomove_pathomove_H_
#define pathomove_pathomove_H_

#include <Rcpp.h>

#include "agent_def.h"
#include "helpers.h"
#include "agent_dyn.h"
#include "landscape.h"
#include "network.h"
#include "parameters.h"
#include "pathospread.h"
#include "simulations.h"

#endif  // pathomove_pathomove_H_

// Undef FALSE which may be defined as integer in one of the imported third
// party headers.
// This solution copied from https://github.com/RcppCore/Rcpp/issues/846
#ifdef FALSE
  #undef FALSE
#endif
