// Copyright 2022 Pratik R Gupte. See repository licence in LICENSE.md.
// Generated by using Rcpp::compileAttributes() and manually modified

#ifndef pathomove_pathomove_H_
#define pathomove_pathomove_H_

#include <Rcpp.h>

#include "agent_def.h"
#include "agent_dyn.h"
#include "landscape.h"
#include "network.h"
#include "parameters.h"
#include "pathospread.h"
#include "simulations.h"

#endif  // pathomove_pathomove_H_
