---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# make landscapes
# load libs
library(data.table)
library(stringr)
library(ggplot2)
library(socialitymodel)
```

```{r}
# test fun
export_test_landscapes(3, 5, 100, 1)
```

## Export landscapes

```{r}
# landscape size
landsize = 100
# make dataframe of options
params = CJ(clusters = c(1, seq(25, 100, 25)),
            dispersal = landsize * seq(0, 0.05, 0.01))

```

```{r}
invisible(
  Map(export_test_landscapes,
    params$clusters, params$dispersal, landsize, 3)
)
```

## Read files

```{r}
# read lookup
lookup = fread("data/test_landscape/test_landscape_lookup.csv")

# read data
data = copy(lookup)

data[, land := lapply(
  filename,
  function(x) {
    fread(glue::glue('data/test_landscape/{x}.csv'))
  })
  ]
```

```{r}
# unnest
data[, filename := NULL]

data = data[, unlist(land, recursive = FALSE),
     by = c("clusters", "dispersal", "replicate")]

# count per 100th of size
data_summary = copy(data)

# round value
data_summary[, `:=`(
  x = round(x, -1),
  y = round(y, -1)
)]
# count items
data_summary <- data_summary[, .N, by = c("x", "y",
                                          "clusters",
                                          "dispersal",
                                          "replicate")]
```

```{r}
# export data
fwrite(data_summary, file = "data/data_landscapes_for_moran.csv")
```

## plot examples

```{r}
ggplot(data_summary[replicate == 1])+
  geom_tile(aes(x, y, fill = N))+
  scale_fill_distiller(palette = "YlOrRd", 
                         trans = "log10", 
                         direction = 1)+
  facet_grid(clusters~dispersal)+
  theme_test()+
  coord_cartesian(expand = F)
```

