---

---

```{r}
# for plotting
library(data.table)
library(ggplot2)
library(patchwork)

# for landscape
library(snevo)
```

Make landscape combinations.

```{r}
parameters = c(1, 3)

lands = lapply(
    parameters,
    function(cs) {
        snevo::get_test_landscape(
            nItems = 2000,
            landsize = 100,
            nClusters = 100,
            clusterSpread = cs,
            regen_time = 50
        )
    }
)

lands = Map(
    lands,
    parameters,
    f = function(df, p) {
        setDT(df)
        df[, cluster_spread := p]
    }
)

lands = rbindlist(lands)
```

```{r}
fig_land = 
    ggplot(lands)+
    geom_point(
        aes(x, y, col = tAvail),
        size = 0.3,
        alpha = 0.5
    )+
    colorspace::scale_colour_binned_sequential(
        palette = "Batlow",
        rev=F,
        name = "time until\navailable",
        breaks = c(0, 5, 10, 20)
    )+
    facet_grid(
        ~cluster_spread,
        labeller = labeller(
            cluster_spread = c(
                "1" = "Patchy",
                "1.5" = "Intermediate",
                "3" = "Homogeneous"
            )
        )
    )+
    theme_test()+
    theme(
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        strip.text = element_text(
            face = "italic"
        ),
        legend.key.width = unit(5, "mm"),
        legend.key.height = unit(2, "mm"),
        legend.position = "top"
    )+
    coord_equal(
        expand = F
    )
fig_land
# save figure
ggsave(
    fig_land,
    file = "figures/fig_land.png",
    height = 60,
    width = 90,
    units = "mm"
)
```