# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns a test landscape.
#'
#' @param nItems How many items.
#' @param landsize Size as a numeric (float).
#' @param nClusters How many clusters, an integer value.
#' @param clusterSpread Dispersal of items around cluster centres.
#' @param regen_time Regeneration time, in timesteps.
#' @return A data frame of the evolved population traits.
get_test_landscape <- function(nItems, landsize, nClusters, clusterSpread, regen_time) {
    .Call(`_pathomove_get_test_landscape`, nItems, landsize, nClusters, clusterSpread, regen_time)
}

#' Runs the pathomove simulation and return a `pathomove_output` object.
#'
#' @description Run the simulation using parameters passed as
#' arguments to the corresponding R function.
#'
#' @param scenario The pathomove scenario: 0 for no pathogen, 1 for 
#' persistent introduction across generations, 
#' 2 for a single introduction,
#' and 3 for sporadic introductions drawn from a geometric distribution
#' specified by `spillover_rate`.
#' @param popsize The population size.
#' @param nItems How many food items on the landscape.
#' @param landsize The size of the landscape as a numeric (double).
#' @param nClusters Number of clusters around which food is generated.
#' @param clusterSpread How dispersed food is around the cluster centre.
#' @param tmax The number of timesteps per generation.
#' @param genmax The maximum number of generations per simulation.
#' @param g_patho_init The generation in which to begin introducing the pathogen.
#' @param range_food The sensory range for food.
#' @param range_agents The sensory range for agents.
#' @param range_move The movement range for agents.
#' @param handling_time The handling time.
#' @param regen_time The item regeneration time.
#' @param pTransmit Probability of transmission.
#' @param initialInfections Agents infected per event.
#' @param costInfect The per-timestep cost of pathogen infection.
#' @param multithreaded Boolean. Whether multithreading using TBB to be used.
#' @param dispersal A float value; the standard deviation of a normal
#' distribution centred on zero, which determines how far away from its parent
#' each individual is initialised. The standard value is 5 percent of the
#' landscape size (\code{landsize}), and represents local dispersal.
#' Setting this to 10 percent is already almost equivalent to global dispersal.
#' @param infect_percent A boolean value; whether the infection depletes a
#' percentage of daily energy (\code{TRUE}) or whether a fixed value 
#' (\code{FALSE}) is subtracted from net energy.
#' For \code{infect_percent = TRUE}, the net energy remaining after \code{T} 
#' timesteps of infection is \code{N * (1 - cost_infect) ^ T}, where \code{N}
#' is total intake.
#' For \code{infect_percent = FALSE}, the net energy remaining after \code{T} 
#' timesteps of infection is \code{N - (cost_infect * T)}, where \code{N}
#' is total intake.
#' @param vertical Should the pathogen be transmitted vertically? Should be
#' set to `TRUE` for a realistic implementation of scenario 3, _single spillover_.
#' @param reprod_threshold Boolean, should individuals with negative energy reproduce.
#' @param mProb The probability of mutation. The suggested value is 0.01.
#' While high, this may be more appropriate for a small population; change this
#' value and \code{popsize} to test the simulation's sensitivity to these values.
#' @param mSize Controls the mutational step size, and represents the scale
#' parameter of a Cauchy distribution.
#' @param spillover_rate For scenario 3, the probability parameter _p_ of a
#' geometric distribution from which the number of generations until the next
#' pathogen introduction are drawn.
#' @return An S4 class, `pathomove_output`, with simulation outcomes.
run_pathomove <- function(scenario, popsize, nItems, landsize, nClusters, clusterSpread, tmax, genmax, g_patho_init, range_food, range_agents, range_move, handling_time, regen_time, pTransmit, initialInfections, costInfect, multithreaded, dispersal, infect_percent, vertical, reprod_threshold, mProb, mSize, spillover_rate) {
    .Call(`_pathomove_run_pathomove`, scenario, popsize, nItems, landsize, nClusters, clusterSpread, tmax, genmax, g_patho_init, range_food, range_agents, range_move, handling_time, regen_time, pTransmit, initialInfections, costInfect, multithreaded, dispersal, infect_percent, vertical, reprod_threshold, mProb, mSize, spillover_rate)
}

