# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Make landscapes with discrete food items in clusters.
#'
#' @description Makes landscape and writes them to file with unique id.
#'
#' @param foodClusters Number of clusters around which food is generated.
#' @param clusterDispersal How dispersed food is around the cluster centre.
#' @param landsize The size of the landscape as a numeric (double).
#' @param replicates How many replicates.
#' @return Nothing. Runs simulation.
export_test_landscapes <- function(foodClusters, clusterDispersal, landsize, replicates) {
    invisible(.Call(`_snevo_export_test_landscapes`, foodClusters, clusterDispersal, landsize, replicates))
}

#' Runs the sociality model simulation.
#'
#' @description Run the simulation using parameters passed as
#' arguments to the corresponding R function.
#' 
#' @param popsize The population size.
#' @param genmax The maximum number of generations per simulation.
#' @param tmax The number of timesteps per generation.
#' @param foodClusters Number of clusters around which food is generated.
#' @param clusterDispersal How dispersed food is around the cluster centre.
#' @param landsize The size of the landscape as a numeric (double).
#' @return A data frame of the evolved population traits.
do_simulation <- function(popsize, genmax, tmax, foodClusters, clusterDispersal, landsize) {
    .Call(`_snevo_do_simulation`, popsize, genmax, tmax, foodClusters, clusterDispersal, landsize)
}

#' Export a population.
#'
#' @param popsize The population size.
export_pop <- function(popsize) {
    .Call(`_snevo_export_pop`, popsize)
}

